#!/bin/sh

set -eu

PROGNAME=$(basename $0)
BASEDIR=$(cd $(dirname $0); pwd)

IMAGE=masnagam/docker-compose
PLATFORM=
TAG=latest
CONTAINER=

if [ "$(uname)" != Linux ] || id -nG | grep -q docker; then
    DOCKER='docker'
else
    DOCKER='sudo docker'
fi

help() {
    cat <<EOF >&2
Get docker-compose

Usage:
  get-docker-compose -h | --help
  get-docker-compose [--platform <platform>] [tag]

Options:
  -h, --help
    Show help

  --platform <platform>
    Platform like linux/amd64.

Arguments:
  tag [default: $TAG]
    One of tags listed in https://hub.docker.com/r/masnagam/docker-compose/tags.

Description:
  This script extracts docker-compose a Docker image downloaded from
  masnagam/docker-compose:\$tag and outputs it to STDOUT.

  The docker-compose is extracted as a TAR archive.  Therefore, it has to be
  expanded by an archiver program like tar in order to extract docker-compose.

  The downloaded Docker image will be removed automatically.

Examples:
  Install the latest version of docker-compose into /usr/local/bin:

    get-docker-compose | sudo tar -x -C /usr/local/bin

  Extract docker-compose for a remote aarch64 machine, and copy it via SSH

    get-docker-compose --platform=linux/arm64/v8 | ssh \$REMOTE tar -x
EOF
    exit 0
}

error() {
    echo "$1" >&2
    exit 1
}

clean() {
    sleep 1
    if [ -n "$CONTAINER" ]; then
        $DOCKER container rm -f "$CONTAINER"
    fi
    $DOCKER image rm -f $IMAGE:$TAG
}

while [ $# -gt 0 ]
do
    case "$1" in
        '-h' | '--help')
            help
            ;;
        '--platform')
            PLATFORM="$2"
            shift 2
            ;;
        *)
            TAG="$1"
            break
            ;;
    esac
done

trap "clean" EXIT INT TERM

CREATE_OPTS=
if [ -n "$PLATFORM" ]; then
    CREATE_OPTS="--platform $PLATFORM"
fi

CONTAINER=$($DOCKER create $CREATE_OPTS $IMAGE)
$DOCKER cp $CONTAINER:/usr/local/bin/docker-compose -
