#!/bin/sh

set -eu

PROGNAME=$(basename $0)
BASEDIR=$(cd $(dirname $0); pwd)

TAG=latest

if [ "$(uname)" != Linux ] || id -nG | grep -q docker; then
    DOCKER='docker'
else
    DOCKER='sudo docker'
fi

help() {
    cat <<EOF >&2
Get docker-compose

USAGE:
  $PROGNAME -h | --help
  $PROGNAME [tag]

OPTIONS:
  -h, --help
    Show help

ARGUMENTS:
  tag (default: $TAG)
    One of tags listed in https://hub.docker.com/r/masnagam/docker-compose/tags.

DESCRIPTION:
  This script extracts docker-compose a Docker image downloaded from
  masnagam/docker-compose:\$tag and outputs it to STDOUT.

  The docker-compose is extracted as a TAR archive.  Therefore, it has to be
  expanded by an archiver program like tar in order to extract docker-compose.

  The downloaded Docker image will be removed automatically.

Example
  Install the latest version of docker-compose into /usr/local/bin:

    $PROGNAME | sudo tar -x -C /usr/local/bin

  Extract docker-compose for a remote machine, and copy it via SSH

    $PROGNAME 1.25.4-debian-arm64v8 | ssh $REMOTE tar -x
EOF
    exit 0
}

error() {
    echo "$1" >&2
    exit 1
}

clean() {
    sleep 1
    if [ -n "$CONTAINER" ]; then
        $DOCKER container rm -f "$CONTAINER"
    fi
    $DOCKER image rm -f $IMAGE
}

while [ $# -gt 0 ]
do
    case "$1" in
        '-h' | '--help')
            help
            ;;
        *)
            break
            ;;
    esac
done

if [ -n "$1" ]; then
    TAG="$1"
fi

IMAGE=masnagam/docker-compose:$TAG
CONTAINER=

trap "clean" EXIT

CONTAINER=$($DOCKER create $IMAGE)
$DOCKER cp $CONTAINER:/usr/local/bin/docker-compose -
