#!/bin/sh

set -eu

PROGNAME=$(basename $0)
BASEDIR=$(cd $(dirname $0); pwd)

DKMS=no
VERSION=master
LINUX_HEADERS=
ACTION=
DEPS="gcc make unzip"

help() {
    cat <<EOF >&2
Install/Uninstall nns779/px4_drv

Usage:
  $PROGNAME -h | --help
  $PROGNAME [--dkms] [--tag <version>] install
  $PROGNAME [--dkms] [--tag <version>] uninstall
  $PROGNAME [--dkms] [--tag <version>] update

Options:
  -h, --help
    Show help.

  --dkms
    Use DKMS.

  --tag <version> [default: $VERSION]
    Version to install.

Actions:
  install
    Install the driver.

  uninstall
    Uninstall the driver.

  update
    Update the driver.  Make sure the driver has already been installed before
    updating.
EOF
    exit 0
}

error() {
    echo "$1" >&2
    exit 1
}

install_firmware() {
    echo "Installing firmware..."
    (cd /tmp/px4_drv/fwtool \
     && make -j $(nproc) \
     && wget http://plex-net.co.jp/plex/pxw3u4/pxw3u4_BDA_ver1x64.zip -O pxw3u4_BDA_ver1x64.zip \
     && unzip -oj pxw3u4_BDA_ver1x64.zip pxw3u4_BDA_ver1x64/PXW3U4.sys \
     && ./fwtool PXW3U4.sys it930x-firmware.bin \
     && sudo mkdir -p /lib/firmware \
     && sudo cp it930x-firmware.bin /lib/firmware/)
}

uninstall_firmware() {
    echo "Uninstalling firmware..."
    sudo rm /lib/firmware/it930x-firmware.bin
}

install_dkms_driver() {
    echo "Installing driver with dkms..."
    (cd /tmp/px4_drv \
     && sudo cp -a ./ /usr/src/px4_drv-0.2.1 \
     && sudo dkms add px4_drv/0.2.1 \
     && sudo dkms install px4_drv/0.2.1)
}

uninstall_dkms_driver() {
    echo "Uninstalling driver with dkms..."
    sudo dkms remove px4_drv/0.2.1 --all
    sudo rm -rf /usr/src/px4_drv-0.2.1
}

install_driver() {
    echo "Installing driver..."
    (cd /tmp/px4_drv/driver && make && sudo make install)
}

uninstall_driver() {
    echo "Uninstalling driver..."
    (cd /tmp/px4_drv/driver && sudo make uninstall)
}

while [ $# -gt 0 ]
do
    case "$1" in
        '-h' | '--help')
            help
            ;;
        '--dkms')
            DKMS=yes
            shift
            ;;
        '--tag')
            VERSION="$2"
            shift 2
            ;;
        'install')
            ACTION=install
            break
            ;;
        'uninstall')
            ACTION=uninstall
            break
            ;;
        'update')
            ACTION=update
            break
            ;;
    esac
done

if [ -z "$ACTION" ]; then
    error "Specify action (install|uninstall|update)"
fi

if [ "$DKMS" = yes ]; then
    DEPS="$DEPS dkms"
fi

echo "Installing deps..."
sudo apt-get update -qq
sudo apt-get install -y -qq --no-install-recommends $DEPS

mkdir /tmp/px4_drv
trap "rm -rf /tmp/px4_drv" EXIT

echo "Downloading $VERSION..."
wget https://github.com/nns779/px4_drv/tarball/$VERSION -O - | \
    tar -zx -C /tmp/px4_drv --strip-components=1

case "$ACTION" in
    'install')
        install_firmware
        if [ "$DKMS" = yes ]; then
            install_dkms_driver
        else
            install_driver
        fi
        ;;
    'uninstall')
        if [ "$DKMS" = yes ]; then
            uninstall_dkms_driver
        else
            uninstall_driver
        fi
        uninstall_firmware
        ;;
    'update')
        if [ "$DKMS" = yes ]; then
            uninstall_dkms_driver
            uninstall_firmware
            install_firmware
            install_dkms_driver
        else
            uninstall_driver
            uninstall_firmware
            install_firmware
            install_driver
        fi
        ;;
esac

echo "Done"
