#!/bin/sh

set -eu

PROGNAME=$(basename $0)
BASEDIR=$(cd $(dirname $0); pwd)

# Original: https://github.com/nns779/px4_drv
GITHUB_URL=https://github.com/tsukumijima/px4_drv

DKMS=no
VERSION=0.4.4
LINUX_HEADERS=
ACTION=
DEPS="ca-certificates curl gcc make unzip"

help() {
  cat <<EOF >&2
Install/Uninstall px4_drv

Usage:
  $PROGNAME -h | --help
  $PROGNAME [--dkms] [--tag <version>] install
  $PROGNAME [--dkms] uninstall
  $PROGNAME [--dkms] [--tag <version>] update

Options:
  -h, --help
    Show help.

  --dkms
    Use DKMS.

  --tag <version> [default: $VERSION]
    Version to install.

Actions:
  install
    Install the driver.

  uninstall
    Uninstall the driver.

  update
    Update the driver.  Make sure the driver has already been installed before
    updating.
EOF
  exit 0
}

error() {
  echo "$1" >&2
  exit 1
}

distro() {
  cat /etc/os-release | grep -E '^ID=' | cut -d '=' -f 2
}

install_firmware() {
  echo "Installing firmware..."
  (cd /tmp/px4_drv/fwtool \
   && make -j $(nproc) \
   && curl http://plex-net.co.jp/plex/pxw3u4/pxw3u4_BDA_ver1x64.zip -fSL >pxw3u4_BDA_ver1x64.zip \
   && unzip -oj pxw3u4_BDA_ver1x64.zip pxw3u4_BDA_ver1x64/PXW3U4.sys \
   && ./fwtool PXW3U4.sys it930x-firmware.bin \
   && sudo mkdir -p /lib/firmware \
   && sudo cp it930x-firmware.bin /lib/firmware/)
}

uninstall_firmware() {
  echo "Removing firmware..."
  sudo rm -f /lib/firmware/it930x-firmware.bin
}

install_dkms_driver() {
  echo "Installing px4_drv/$VERSION using dkms..."
  (cd /tmp/px4_drv \
   && sudo cp -a ./ /usr/src/px4_drv-$VERSION \
   && sudo dkms add -m px4_drv -v $VERSION \
   && sudo dkms install -m px4_drv -v $VERSION)
}

uninstall_dkms_driver() {
  # Uninstall only the first px4_drv.
  # Run multiple times if you install multiple versions of px4_drv.
  V=$(sudo dkms status | grep px4_drv | head -1 | cut -d ',' -f 1 | cut -d '/' -f 2)
  if [ -n $V ]
  then
    echo "Removing px4_drv/$V installed using dkms..."
    sudo dkms remove -m px4_drv -v $V --all
    sudo rm -rf /usr/src/px4_drv-$V
  else
    echo "No px4_drv installed"
  fi
}

install_driver() {
  echo "Installing px4_drv/$VERSION..."
  (cd /tmp/px4_drv/driver && make && sudo make install)
}

uninstall_driver() {
  V=$(sudo modinfo px4_drv | grep -E '^version' | cut -d ':' -f 2 | tr -d ' ')
  if [ -n $V ]
  then
    echo "Removing px4_drv/$V..."
    (cd /tmp/px4_drv/driver && sudo make uninstall)
  else
    echo "No px4_drv installed"
  fi
}

while [ $# -gt 0 ]
do
  case "$1" in
    '-h' | '--help')
      help
      ;;
    '--dkms')
      DKMS=yes
      shift
      ;;
    '--tag')
      VERSION="$2"
      shift 2
      ;;
    'install')
      ACTION=install
      break
      ;;
    'uninstall')
      ACTION=uninstall
      break
      ;;
    'update')
      ACTION=update
      break
      ;;
  esac
done

if [ -z "$ACTION" ]
then
  error "Specify action (install|uninstall|update)"
fi

if [ "$DKMS" = yes ]
then
  DEPS="$DEPS dkms"
fi

echo "Installing deps..."
case "$(distro)" in
  arch)
    sudo pacman -S --noconfirm $DEPS
    ;;
  debian)
    sudo apt-get update -qq
    sudo apt-get install -y -qq --no-install-recommends $DEPS
    ;;
esac

mkdir /tmp/px4_drv
trap "rm -rf /tmp/px4_drv" EXIT

echo "Downloading $VERSION..."
curl $GITHUB_URL/tarball/v$VERSION -fSL | tar -zx -C /tmp/px4_drv --strip-components=1

echo "Enable workqueue"
sed -i 's/make KVER=${kernelver} /make KVER=${kernelver} ITEDTV_BUS_USE_WORKQUEUE=1 /' /tmp/px4_drv/dkms.conf

# CLEAN was deprecated.
# See https://github.com/dell/dkms/commit/cdad565004349b78b7164fc2195fe70674d2b148
if expr "$(dkms --version)" '>' 'dkms-3.1.7' >/dev/null
then
  sed -i '/^CLEAN=.*/d' /tmp/px4_drv/dkms.conf
fi

case "$ACTION" in
  'install')
    install_firmware
    if [ "$DKMS" = yes ]
    then
      install_dkms_driver
    else
      install_driver
    fi
    ;;
  'uninstall')
    if [ "$DKMS" = yes ]
    then
      uninstall_dkms_driver
    else
      uninstall_driver
    fi
    uninstall_firmware
    ;;
  'update')
    if [ "$DKMS" = yes ]
    then
      uninstall_dkms_driver
      uninstall_firmware
      install_firmware
      install_dkms_driver
    else
      uninstall_driver
      uninstall_firmware
      install_firmware
      install_driver
    fi
    ;;
esac

echo "Done"
