#!/bin/sh

set -eu

VERSION=1.3.2
DEPS="autoconf automake gcc make tar wget"

echo "Installing deps..."
sudo apt-get update -qq
sudo apt-get install -y -qq --no-install-recommends $DEPS

SRCDIR=$(mktemp -d)
trap "rm -rf $SRCDIR" EXIT INT TERM

echo "Downloading recdvb-$VERSION.tgz..."
wget http://www13.plala.or.jp/sat/recdvb/recdvb-$VERSION.tgz -O - | \
  tar -zx -C $SRCDIR --strip-components=1

echo "Building recdvb..."
(cd $SRCDIR; ./autogen.sh && ./configure --prefix=/usr/local && make)

echo "Installing recdvb..."
(cd $SRCDIR; sudo make install)

recdvb --version
